CREATE TABLE EMPLOYEE (
Fname VARCHAR(15),
MINIT CHAR(1),
Lname VARCHAR(15),
Ssn CHAR(9) NOT NULL,
Bdate DATE,
Address VARCHAR(30),
Sex CHAR,
Salary DECIMAL(10,2),
Super_ssn CHAR(9),
Dno INT,
PRIMARY KEY (Ssn)
);

CREATE TABLE DEPARTMENT (
Dname VARCHAR(15),
Dnumber INT NOT NULL,
Mgr_ssn CHAR(9),
Mgr_start_date DATE,
PRIMARY KEY (Dnumber)
);

CREATE TABLE DEPT_LOCATIONS (
Dnumber INT NOT NULL,
Dlocation VARCHAR(15) NOT NULL,
PRIMARY KEY (Dnumber,Dlocation)
);

CREATE TABLE PROJECT (
Pname VARCHAR(15),
Pnumber INT NOT NULL,
Plocation VARCHAR(15),
Dnum INT,
PRIMARY KEY (Pnumber,Plocation)
);

CREATE TABLE WORKS_ON (
Essn CHAR(9) NOT NULL,
Pno INT NOT NULL,
Hours DECIMAL(3,1),
PRIMARY KEY (Essn,Pno)
);

CREATE TABLE DEPENDENT (
Essn CHAR(9) NOT NULL,
Dependent_name VARCHAR(15) NOT NULL,
Sex CHAR,
Bdate DATE,
Relationship VARCHAR(8),
PRIMARY KEY (Essn,Dependent_name)
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE1
FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE2
FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT FK_DEPT_LOCATIONS
FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE PROJECT
ADD CONSTRAINT FK_PROJECT
FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WORKS_ON1
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_WORK_ON2
FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

ALTER TABLE DEPENDENT
ADD CONSTRAINT FK_DEPENDENT
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);